### PR TITLE
Uninstall modemmanager to avoid it grabbing the board

### PR DESCRIPTION
**Pull request by bbaltz505**
CODK-73

### CODE REVIEW

**Comment by eriknyquist** [comment]
What if somebody needs modemmanager? They wouldn't have any way of knowing that running "install-dep" will UNinstall modemmanager.

**Comment by bbaltz505** [comment]
true. I wasn't sure how popular modemmanager was. The udev rules are supposed to be excluding the boards from use by modemmanager. It might be better to just have camp participants to manually remove the package.

**Comment by calvinatintel** [comment]
I think it's okay to blow away since we instruct the users to create a new VM for CODK

**Comment by eriknyquist** [comment]
Well someone might be on native, like me. I think it'd OK to blow away, just make sure the user knows that will happen before they run install-dep. 
Can we add a warning in the docs maybe?

**Comment by eriknyquist** [comment]
Well someone might be on native, like me. I think it'd OK to blow away, just make sure the user knows that will happen before they run install-dep. 
Can we add a warning in the docs maybe?

**Pull request merged**
