### PR TITLE
Fix "make upload" failing the ARC part

### PR DESCRIPTION
**Pull request by alext-mkrs**
Very simple (KISS) fix for `make upload` consistently failing the ARC part, at least on my setup.

### CODE REVIEW

**Comment by calvinatintel** [comment]
Ah, we've missed this change on CODK-A.
Here's the equivalent section to CODK-M: https://github.com/01org/CODK-M/blob/master/Makefile#L120
Can you please change the code to match CODK-M?
Thanks!

**Comment by alext-mkrs** [comment]
Indeed :) Sure, will do.

**Comment by alext-mkrs** [comment]
Updated to match CODK-M.

**Review by calvinatintel — APPROVED** [review]

**Comment by calvinatintel** [comment]
Thank you for your contributions!

**Pull request merged**
