### PR TITLE
Add top level Makefile to fetch and setup

### PR DESCRIPTION
**Pull request by calvinatintel**
@bbaltz505 Need to add a whole bunch more

### CODE REVIEW

**Comment by calvinatintel** [comment]
@bbaltz505 Do you think we need top level `compile` and `upload` targets?

**Comment by bbaltz505** [comment]
eventually. For firmware, it's easy to build the FW
firmware: check-codk
        $(MAKE) -C $(FWPROJ_DIR) setup image
The ARC side is a bit more involved.

**Comment by calvinatintel** [comment]
Commits crushed into one

**Comment by calvinatintel** [comment]
Everything is good except for `make upload-software-dfu`. When it's called as a part of `make upload` chain, it's run right after `make upload-firmware-dfu` and crashes.

**Comment by calvinatintel** [comment]
Merging in since `make upload-software-dfu` will be addressed in `CODK-A-Software` repo

**Pull request merged**
