### PR TITLE
Add debug info to README

### PR DESCRIPTION
**Pull request by calvinatintel**
@eriknyquist @bigdinotech @bbaltz505 @intel-larry

### CODE REVIEW

**Comment by eriknyquist** [comment]
Couldn't get libc6-dev-i386 to install on 16, installing 14 now....

**Comment by eriknyquist** [comment]
Wasn't able to get debug working, I get the following complaint from GDB after trying to connect to the remote target

```
enyquist:$ make debug-software
/home/enyquist/dev/CODK/CODK-A//software/arc32/bin/arc-elf32-gdb         /home/enyquist/dev/CODK/CODK-A//software/examples/Blink//arc-debug.elf
GNU gdb (ARCompact/ARCv2 ISA elf32 toolchain arc-2016.03-rc2) 7.10
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "--host=x86_64-unknown-linux-gnu --target=arc-elf32".
Type "show configuration" for configuration details. 
For bug reporting instructions, please see:
<https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/issues>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /home/enyquist/dev/CODK/CODK-A//software/examples/Blink//arc-    debug.elf...done.
(gdb) target remote localhost:3334
Remote debugging using localhost:3334
Error: Couldn't find core register feature in supplied target description.warning: Architecture rejected       target-supplied description
0xffff93ff in ?? ()
(gdb) s
Cannot find bounds of current function
(gdb) s
Cannot find bounds of current function
(gdb) 
```

**Comment by eriknyquist** [comment]
Starting the server looked fine, here's the output from it

```
enyquist:$ make debug-server
/home/enyquist/dev/CODK/CODK-A//flashpack/bin/openocd.l64 -f /home/enyquist/dev/CODK/CODK-    A//flashpack/scripts/interface/ftdi/flyswatter2.cfg -f /home/enyquist/dev/CODK/CODK-    A//flashpack/scripts/board/quark_se.cfg
Open On-Chip Debugger 0.8.0-dev-ga422c7e (2016-05-23-16:55)
Licensed under GNU GPL v2
For bug reports, read
http://openocd.sourceforge.net/doc/doxygen/bugs.html
Info : only one transport option; autoselect 'jtag' 
adapter speed: 1000 kHz
trst_only separate trst_push_pull
Info : clock speed 1000 kHz
Info : JTAG tap: quark_se.cltap tap/device found: 0x0e765013 (mfg: 0x009, part: 0xe765, ver: 0x0)
Enabling arc core tap
Info : JTAG tap: quark_se.arc-em enabled
Polling target arc-em.cpu failed, GDB will be halted. Polling again in 100ms
Enabling lmt core tap
Polling target arc-em.cpu failed, GDB will be halted. Polling again in 300ms
Info : JTAG tap: quark_se.lmt enabled
Processor type: arc-em
redirect to PM, tapstatus=0x00300c14
unknown break reason at 0x40016552
Polling target arc-em.cpu succeeded again
```

**Comment by eriknyquist** [comment]
My mistake, I was connecting to the wrong targets... should be 3333 for software, and 3334 for firmware. It seems to work now, but I have one suggestion... when you start the server, it does halt the board, but it doesn't reset first so I usually get dumped here when I connect to the target;

```
(gdb) target remote localhost:3333
Remote debugging using localhost:3333
Error: Couldn't find core register feature in supplied target description.warning: Architecture rejected target-supplied description
0x40036c32 in delay (msec=<optimized out>) at /home/enyquist/dev/CODK/CODK-    A//software/corelibs/cores/arduino/wiring.c:52
52      while (getTimeStampClks() - initial_timestamp < delay_clks) {
(gdb) 
```

If possible, it would be a little nicer to drop the user at a breakpoint on the first line of Blink.ino.cpp

**Comment by calvinatintel** [comment]
Should I include the next commands for typical use case in README? Or is this a common knowledge among c++ developers?

```
(gdb) monitor reset
(gdb) continue
(gdb) ^C (interrupt)
(gdb) step
```

**Comment by eriknyquist** [comment]
No, I don't think you need to, just thought you could have the script do a reset and halt, instead of just a halt.

Also, I'm not sure if I'm doing something wrong, but 'reset halt' seems to put me in a different place every time;

```
(gdb) monitor reset halt
JTAG tap: quark_se.cltap tap/device found: 0x0e765013 (mfg: 0x009, part: 0xe765, ver: 0x0)
Enabling arc core tap
JTAG tap: quark_se.arc-em enabled
Enabling lmt core tap
JTAG tap: quark_se.lmt enabled
target state: halted
target halted due to debug-request at 0x400164d5 in protected mode
target state: halted
target halted due to debug-request at 0x0000fff0 in real mode
target state: halted
(gdb) list
34  {
35      uint32_t time_stamp;
36      int key = interrupt_lock();
37      uint64_t ret = timer0_overflows;
38      time_stamp = aux_reg_read(ARC_V2_TMR0_COUNT);
39      if (aux_reg_read(ARC_V2_TMR0_CONTROL) & (0x01 << 3)) {
40          time_stamp = aux_reg_read(ARC_V2_TMR0_COUNT);
41          ret++;
42      }
43      interrupt_unlock(key);
(gdb) monitor reset halt
JTAG tap: quark_se.cltap tap/device found: 0x0e765013 (mfg: 0x009, part: 0xe765, ver: 0x0)
Enabling arc core tap
JTAG tap: quark_se.arc-em enabled
Enabling lmt core tap
JTAG tap: quark_se.lmt enabled
target state: halted
target halted due to debug-request at 0x0000fff0 in real mode
target state: halted
(gdb) list
44      return ((ret << 32) | time_stamp);
45  }
46   
47  void delay(uint32_t msec)
48  {
49      uint64_t initial_timestamp = getTimeStampClks();
50      uint64_t delay_clks = msec * MS_TO_CLKS;
51  
52      while (getTimeStampClks() - initial_timestamp < delay_clks) {
53          yield();
(gdb)
```

Any idea what's going on there?

**Comment by calvinatintel** [comment]
Sorry, no idea. gdb is beyond my realm of knowledge.

**Comment by eriknyquist** [comment]
@bbaltz505 any thoughts on the above?

**Comment by bbaltz505** [comment]
This is the Blink example? It seems like it's stopping in various places during the "delay" - since most of the sketch is waiting. I'm not a gdb CLI guru but I was able to set a breakpoint in the main part of the sketch and it seemed to stop at the right spot.

**Comment by eriknyquist** [comment]
Yes, this is the blink example. breakpoints were working fine, just "reset halt" didn't always put me in the same place..... not sure if that's a problem or if I'm missing something

**Comment by calvinatintel** [comment]
cherry-picked

**Pull request closed without merging**
